### ISSUE TITLE
Constant "problem" reported about CPU load

### ISSUE THREAD

**Issue by TurkeyMan** [albin-lindstrom/zabbix-edgemax-template#11]
After hacking the template, I made it work.
I added my router; an ER-8-XG, and it keeps reporting a "PROBLEM": `Load average is too high (per CPU load over 1.5 for 1m)`
The router hovers between 1-4% total CPU load. My guess is it's complaining when any core exceeds 1.5% CPU load, which happens all the time.
Is this intended? Why is the template setup to complain about 1.5% CPU usage?
Perhaps I misinterpreted the error?

**Comment by albinbatman** [comment]
Hi again,

No, it is complaining because the [1-minute load average](https://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html) is above the macro value LOAD_AVG_PER_CPU.MAX.WARN. I'd suggest looking at the value you are currently retrieving from the device whilst it is doing a high workload, then adjust the macro value LOAD_AVG_PER_CPU.MAX.WARN accordingly (or calculate it a bit loosely with [this formula](https://superuser.com/questions/729634/load-average-and-processor-count))
